name: Mirror Sourcegraph to Incremental Indexing Fork

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    environment: 'Sync'
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:sourcegraph/sourcegraph.git"
          destination-repo: "git@github.com:sgtest/sourcegraph-incremental-indexing-fork.git"
